server:
  port: 8123

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: east1
    perfer-ip-address: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://east2:8124/eureka/