eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8123/eureka/,http://127.0.0.1:8124/eureka/,
server:
  port: 8763
spring:
  application:
    name: service-hi
  zipkin:
    base-url: http://localhost:9411